#PASTELERÍA QUE A LAS 6AM 
#LA LLEGADA DE CLIENTES SIGUE UN PROCESO DE POISSON 
#CON 30 CLIENTES POR HORA 
#ENCONTRAR LA PROBABILIDAD DE QUE 65 CLIENTES 
#LLEGUEN ENTRE LAS 9AM Y 11AM 
#RECORDEMOS QUE LOS PROCESOS DE POISSON EMPIEZAN EN 0 
#P(PN5-N3>65) TIENE INCREMENTOS ESTACIONARIOS 

1-ppois(65,2*30)
#COMLEMENTO 